const serviceToSlugMap: Record<string, string> = {
  // AI/ML Services
  openai: 'openai',
  chatgpt: 'openai',
  'gpt-4': 'openai',
  gpt: 'openai',
  anthropic: 'anthropic',
  claude: 'anthropic',
  gemini: 'googlegemini',
  'google-gemini': 'googlegemini',
  mistral: 'mistral',
  'mistral-ai': 'mistral',
  ollama: 'ollama',
  huggingface: 'huggingface',
  'hugging-face': 'huggingface',
  cohere: 'cohere',
  replicate: 'replicate',
  groq: 'groq',
  perplexity: 'perplexity',
  langchain: 'langchain',
  llamaindex: 'llamaindex',
  'llama-index': 'llamaindex',
  pinecone: 'pinecone',
  weaviate: 'weaviate',
  chroma: 'chroma',
  chromadb: 'chroma',
  qdrant: 'qdrant',
  milvus: 'milvus',
  
  // Data / Analytics
  snowflake: 'snowflake',
  databricks: 'databricks',
  dbt: 'dbt',
  'dbt-labs': 'dbt',
  airflow: 'apacheairflow',
  'apache-airflow': 'apacheairflow',
  spark: 'apachespark',
  'apache-spark': 'apachespark',
  flink: 'apacheflink',
  'apache-flink': 'apacheflink',
  nifi: 'apachenifi',
  'apache-nifi': 'apachenifi',
  looker: 'looker',
  metabase: 'metabase',
  tableau: 'tableau',
  grafana: 'grafana',
  superset: 'apachesuperset',
  'apache-superset': 'apachesuperset',
  clickhouse: 'clickhouse',
  trino: 'trino',
  
  // DevOps / IaC
  argocd: 'argo',
  'argo-cd': 'argo',
  flux: 'flux',
  fluxcd: 'flux',
  pulumi: 'pulumi',
  ansible: 'ansible',
  puppet: 'puppet',
  chef: 'chef',
  packer: 'packer',
  vault: 'vault',
  'hashicorp-vault': 'vault',
  consul: 'consul',
  nomad: 'nomad',
  crossplane: 'crossplane',
  tekton: 'tekton',
  skaffold: 'skaffold',
  kustomize: 'kubernetes',
  
  // Auth / Identity
  auth0: 'auth0',
  okta: 'okta',
  keycloak: 'keycloak',
  clerk: 'clerk',
  
  // Monitoring / Observability
  newrelic: 'newrelic',
  'new-relic': 'newrelic',
  dynatrace: 'dynatrace',
  honeycomb: 'honeycomb',
  signoz: 'signoz',
  jaeger: 'jaeger',
  zipkin: 'apachezipkin',
  loki: 'grafana',
  tempo: 'grafana',
  pyroscope: 'grafana',
  'victoria-metrics': 'victoriametrics',
  
  // Messaging / Streaming
  pulsar: 'apachepulsar',
  'apache-pulsar': 'apachepulsar',
  
  // Storage / CDN
  minio: 'minio',
  ceph: 'ceph',
  fastly: 'fastly',
  akamai: 'akamai',
  bunnycdn: 'bunny',
  bunny: 'bunny',
  'cloudflare-r2': 'cloudflare',
  r2: 'cloudflare',
  backblaze: 'backblaze',
  
  // Frontend Frameworks
  svelte: 'svelte',
  sveltekit: 'svelte',
  solid: 'solid',
  solidjs: 'solid',
  qwik: 'qwik',
  astro: 'astro',
  remix: 'remix',
  htmx: 'htmx',
  
  // Backend Frameworks
  fastify: 'fastify',
  hapi: 'hapi',
  nestjs: 'nestjs',
  elysia: 'elysia',
  bun: 'bun',
  deno: 'deno',
  django: 'django',
  flask: 'flask',
  fastapi: 'fastapi',
  spring: 'spring',
  'spring-boot': 'spring',
  rails: 'rubyonrails',
  'ruby-on-rails': 'rubyonrails',
  fiber: 'go',
  'go-fiber': 'go',
  gin: 'go',

  postgresql: 'postgresql',
  postgres: 'postgresql',
  mysql: 'mysql',
  mariadb: 'mariadb',
  mongodb: 'mongodb',
  mongo: 'mongodb',
  cosmosdb: 'microsoftazure',
  dynamodb: 'amazondynamodb',
  redis: 'redis',
  memcached: 'memcached',
  elasticsearch: 'elasticsearch',
  opensearch: 'opensearch',
  kafka: 'apachekafka',
  rabbitmq: 'rabbitmq',
  activemq: 'apacheactivemq',
  nats: 'nats',
  zeromq: 'zeromq',
  mqtt: 'mqtt',
  cassandra: 'apachecassandra',
  couchdb: 'couchdb',
  sqlite: 'sqlite',
  neo4j: 'neo4j',
  influxdb: 'influxdb',
  timescaledb: 'timescaledb',
  supabase: 'supabase',
  firestore: 'firebase',
  docker: 'docker',
  containerd: 'containerd',
  kubernetes: 'kubernetes',
  k8s: 'kubernetes',
  helm: 'helm',
  istio: 'istio',
  linkerd: 'linkerd',
  docker_compose: 'docker',
  ecs: 'amazonecs',
  eks: 'amazoneks',
  fargate: 'awsfargate',
  ec2: 'amazonec2',
  lambda: 'awslambda',
  s3: 'amazons3',
  rds: 'amazonrds',
  aurora: 'amazonrds',
  sqs: 'amazonsqs',
  sns: 'amazonsns',
  ses: 'amazonses',
  cloudwatch: 'amazoncloudwatch',
  cloudtrail: 'amazoncloudtrail',
  cloudfront: 'amazoncloudfront',
  route53: 'amazonroute53',
  elb: 'amazonelb',
  alb: 'amazonelb',
  nlb: 'amazonelb',
  appconfig: 'awsappconfig',
  secretsmanager: 'awssecretsmanager',
  certificatemanager: 'awscertificatemanager',
  iam: 'awsiam',
  acm: 'awscertificatemanager',
  vpc: 'amazonvpc',
  stepfunctions: 'awsstepfunctions',
  sagemaker: 'amazonsagemaker',
  bedrock: 'amazonbedrock',
  ecr: 'amazonecr',
  ssm: 'awssystemsmanager',
  kinesis: 'amazonkinesis',
  qldb: 'amazonqldb',
  api_gateway: 'amazonapigateway',
  apigateway: 'amazonapigateway',
  aws_api_gateway: 'amazonapigateway',
  amazon_api_gateway: 'amazonapigateway',
  opensearch_service: 'opensearch',
  appsync: 'awsappsync',
  amplify: 'awsamplify',
  device_farm: 'amazondevicefarm',
  code_build: 'awscodebuild',
  code_deploy: 'awscodedeploy',
  code_pipeline: 'awscodepipeline',
  code_commit: 'awscodecommit',
  codecommit: 'awscodecommit',
  codebuild: 'awscodebuild',
  codedeploy: 'awscodedeploy',
  codepipeline: 'awscodepipeline',
  gcp: 'googlecloud',
  google_cloud: 'googlecloud',
  gce: 'googlecomputeengine',
  compute_engine: 'googlecomputeengine',
  app_engine: 'googleappengine',
  appengine: 'googleappengine',
  cloud_run: 'googlecloudrun',
  cloud_functions: 'googlecloudfunctions',
  cloudfunctions: 'googlecloudfunctions',
  gcs: 'googlecloudstorage',
  cloud_storage: 'googlecloudstorage',
  bigquery: 'googlebigquery',
  datastore: 'clouddatastore',
  firestore_gcp: 'firebase',
  spanner: 'cloudspanner',
  cloud_sql: 'cloudsql',
  cloud_memorystore: 'cloudmemorystore',
  memorystore: 'cloudmemorystore',
  cloud_pubsub: 'cloudpubsub',
  pubsub: 'cloudpubsub',
  cloud_tasks: 'cloudtasks',
  cloud_scheduler: 'cloudscheduler',
  cloud_logging: 'cloudlogging',
  stackdriver: 'googlecloud',
  cloud_monitoring: 'googlecloud',
  cloud_trace: 'googlecloud',
  cloud_profiler: 'googlecloud',
  cloud_error_reporting: 'googlecloud',
  identity_platform: 'googleidentityplatform',
  cloud_identity: 'googleidentity',
  service_account: 'googlecloud',
  service_accounts: 'googlecloud',
  iam_gcp: 'googlecloud',
  cloud_iam: 'googlecloud',
  kms: 'cloudkms',
  cloud_kms: 'cloudkms',
  secret_manager: 'secretmanager',
  cloud_armor: 'googlecloudarmor',
  load_balancer: 'googlecloud',
  cloud_cdn: 'googlecloudcdn',
  cloud_vpc: 'googlecloud',
  vpc_peering: 'googlecloud',
  azure: 'microsoftazure',
  app_service: 'microsoftazure',
  appservice: 'microsoftazure',
  azure_vm: 'microsoftvirtualmachines',
  vm: 'microsoftvirtualmachines',
  virtual_machines: 'microsoftvirtualmachines',
  aks: 'kubernetesservice',
  kubernetes_service: 'kubernetesservice',
  container_registry: 'microsoftazure',
  acr: 'microsoftazure',
  azure_functions: 'microsoftazure',
  function_app: 'microsoftazure',
  logic_apps: 'azurelogicapps',
  cosmos_db: 'microsoftazure',
  sql_server: 'microsoftsqlserver',
  sql_database: 'microsoftsqlserver',
  azure_sql: 'microsoftsqlserver',
  postgresql_flexible: 'postgresql',
  mysql_flexible: 'mysql',
  mariadb_flexible: 'mariadb',
  azure_storage: 'microsoftazurestorage',
  blob_storage: 'microsoftazurestorage',
  queue_storage: 'microsoftazurestorage',
  file_share: 'microsoftazurestorage',
  azure_service_bus: 'azureservicebus',
  service_bus: 'azureservicebus',
  event_hubs: 'azureeventhubs',
  event_grid: 'azureeventgrid',
  azure_cache_redis: 'redis',
  api_management: 'azureapimanagement',
  azure_devops: 'azuredevops',
  devops: 'azuredevops',
  repos: 'azuredevops',
  pipelines: 'azuredevops',
  artifacts: 'azuredevops',
  test_plans: 'azuredevops',
  boards: 'azuredevops',
  applicationgateway: 'microsoftazure',
  frontdoor: 'azurefrontdoor',
  cdn: 'azurecdn',
  ddos_protection: 'microsoftazure',
  firewall: 'azurefirewall',
  bastion: 'azurebastion',
  application_insights: 'applicationinsights',
  monitor: 'microsoftazure',
  log_analytics: 'microsoftazure',
  nodejs: 'nodedotjs',
  node: 'nodedotjs',
  python: 'python',
  go: 'go',
  golang: 'go',
  rust: 'rust',
  java: 'java',
  kotlin: 'kotlin',
  scala: 'scala',
  groovy: 'apachegrovy',
  clojure: 'clojure',
  elixir: 'elixir',
  erlang: 'erlang',
  ruby: 'ruby',
  php: 'php',
  laravel: 'laravel',
  symfony: 'symfony',
  yii: 'yiiframework',
  csharp: 'csharp',
  dotnet: 'dotnet',
  fsharp: 'fsharp',
  cpp: 'cplusplus',
  c: 'c',
  swift: 'swift',
  objective_c: 'objectivec',
  perl: 'perl',
  lua: 'lua',
  bash: 'gnubash',
  shell: 'gnubash',
  sh: 'gnubash',
  typescript: 'typescript',
  javascript: 'javascript',
  react: 'react',
  vue: 'vuedotjs',
  angular: 'angular',
  next: 'nextdotjs',
  nextjs: 'nextdotjs',
  nuxt: 'nuxtdotjs',
  gatsby: 'gatsby',
  tailwind: 'tailwindcss',
  bootstrap: 'bootstrap',
  material_ui: 'materialui',
  mui: 'materialui',
  chakra_ui: 'chakraui',
  html5: 'html5',
  css3: 'css3',
  sass: 'sass',
  less: 'less',
  webpack: 'webpack',
  vite: 'vitejs',
  parcel: 'parceljs',
  rollup: 'rollupjs',
  esbuild: 'esbuild',
  gulp: 'gulpjs',
  grunt: 'gruntjs',
  npm: 'npm',
  yarn: 'yarn',
  pnpm: 'pnpm',
  prometheus: 'prometheus',
  datadog: 'datadog',
  elastic: 'elastic',
  logstash: 'logstash',
  kibana: 'kibana',
  splunk: 'splunk',
  sumologic: 'sumo',
  appdynamics: 'appdynamics',
  pingdom: 'pingdom',
  uptimerobot: 'uptimerobot',
  sentry: 'sentry',
  rollbar: 'rollbar',
  bugsnag: 'bugsnag',
  lightstep: 'lightstep',
  nginx: 'nginx',
  apache: 'apache',
  httpd: 'apache',
  caddy: 'caddyserver',
  haproxy: 'haproxy',
  traefik: 'traefikproxy',
  envoy: 'envoyproxy',
  f5: 'f5networks',
  varnish: 'varnish',
  squid: 'squid',
  boundary: 'hashicorpboundary',
  terraform: 'terraform',
  saltstack: 'saltproject',
  jenkins: 'jenkins',
  gitlab_ci: 'gitlab',
  github_actions: 'github',
  circleci: 'circleci',
  travis_ci: 'travisci',
  appveyor: 'appveyor',
  azure_pipelines: 'azuredevops',
  gitlab: 'gitlab',
  github: 'github',
  bitbucket: 'bitbucket',
  gitea: 'gitea',
  gitbucket: 'gitbucket',
  gitolite: 'git',
  subversion: 'subversion',
  svn: 'subversion',
  mercurial: 'mercurial',
  hg: 'mercurial',
  fossil: 'fossil',
  pijul: 'pijul',
  git: 'git',
  google_ai: 'googlegemini',
  hugging_face: 'huggingface',
  modal: 'modal',
  together_ai: 'togetherai',
  stabilityai: 'stabilitydotai',
  stability: 'stabilitydotai',
  deepinfra: 'deepinfra',
  baseten: 'baseten',
  modal_labs: 'modal',
  opentelemetry: 'opentelemetry',
  otel: 'opentelemetry',
  openmetrics: 'prometheus',
  apacheopentelemetry: 'opentelemetry',
  wandb: 'weightsandbiases',
  mlflow: 'mlflow',
  kubeflow: 'kubeflow',
  fivetran: 'fivetran',
  talend: 'talend',
  informatica: 'informatica',
  snaplogic: 'snaplogic',
  mulesoft: 'mulesoft',
  apigee: 'googleapigee',
  kong: 'konginc',
  postman: 'postman',
  insomnia: 'insomnia',
  swagger: 'swaggerio',
  openapi: 'openapiinitiative',
  asyncapi: 'asyncapi',
  graphql: 'graphql',
  rest: 'rest',
  soap: 'soap',
  rpc: 'rpc',
  grpc: 'grpc',
  mqtt_protocol: 'mqtt',
  http: 'http',
  https: 'https',
  ws: 'websockets',
  websocket: 'websockets',
  tcp: 'tcp',
  udp: 'udp',
  dns: 'dns',
  dhcp: 'dhcp',
  bgp: 'bgp',
  ospf: 'ospf',
  vpn: 'openvpn',
  openvpn: 'openvpn',
  wireguard: 'wireguard',
  zerotier: 'zerotier',
  tailscale: 'tailscale',
  cloudflare: 'cloudflare',
  aws_waf: 'awswaf',
  imperva: 'imperva',
  zscaler: 'zscaler',
  crowdstrike: 'crowdstrike',
  snyk: 'snyk',
  sonarqube: 'sonarsource',
  checkmarx: 'checkmarx',
  veracode: 'veracode',
  qualys: 'qualys',
  nessus: 'tenable',
  acunetix: 'acunetix',
  burpsuite: 'portswigger',
  owasp: 'owasp',
  oss_review_toolkit: 'reuse',
  sbom: 'cyclonedx',
  cyclonedx: 'cyclonedx',
  sigstore: 'sigstore',
  cosign: 'sigstore',
  notary: 'thenotaryproject',
  sealed_secrets: 'kubernetes',
  external_secrets: 'externalsecrets',
};

const brandColors: Record<string, string> = {
  postgresql: '#336791',
  mysql: '#005a87',
  mongodb: '#00ed64',
  redis: '#dc382d',
  kafka: '#000000',
  rabbitmq: '#ff6600',
  docker: '#2496ed',
  kubernetes: '#326ce5',
  ec2: '#ff9900',
  lambda: '#ff9900',
  s3: '#ff9900',
  rds: '#ff9900',
  dynamodb: '#ff9900',
  nodejs: '#339933',
  python: '#3776ab',
  go: '#00add8',
  rust: '#ce422b',
  java: '#007396',
  react: '#61dafb',
  vue: '#4fc08d',
  angular: '#dd0031',
  typescript: '#3178c6',
  javascript: '#f7df1e',
  nginx: '#009639',
  github: '#181717',
  gitlab: '#fc6d26',
  terraform: '#623ce4',
  prometheus: '#e6522c',
  grafana: '#f96208',
  elasticsearch: '#005571',
  jenkins: '#d24939',
  openai: '#10a37f',
};

export interface SimpleIconConfig {
  slug: string;
  hexColor?: string;
}

import { AWS_INLINE_SVG } from './aws-inline.js';
import { INLINE_SVG } from './inline-icons.js';

export function getIconURL(service: string, hexColor?: string): string {
  const normalizedService = service.toLowerCase().trim();
  let mappedSlug = serviceToSlugMap[normalizedService];
  
  if (!mappedSlug) {
    const stripped = normalizedService
      .replace(/\([^)]*\)/g, '')
      .replace(/\b(?:aws|amazon|google cloud|gcp|microsoft azure|azure)\b/g, '')
      .replace(/[^a-z0-9]/g, '');
    
    if (stripped) {
      for (const [key, val] of Object.entries(serviceToSlugMap)) {
        if (key.replace(/[^a-z0-9]/g, '') === stripped) {
          mappedSlug = val;
          break;
        }
      }
    }
  }

  // Keyword heuristic — only used for CDN lookup, NOT treated as a definitive mapping.
  // We keep it separate from mappedSlug so truly unknown services still fall through
  // to the data-URI fallback rather than an unverifiable CDN URL.
  let heuristicSlug: string | undefined;
  if (!mappedSlug) {
    if (/auth|login|security|identity/i.test(service)) heuristicSlug = 'keycloak';
    else if (/admin|config|setting|system/i.test(service)) heuristicSlug = 'kubernetes';
    else if (/api|gateway/i.test(service)) heuristicSlug = 'openapiinitiative';
    else if (/job|worker|task|cron|process/i.test(service)) heuristicSlug = 'apacheairflow';
    else if (/\bweb\b|frontend|\bclient\b/i.test(service)) heuristicSlug = 'html5';
  }

  const color = hexColor || brandColors[normalizedService] || '666666';
  const slug = mappedSlug ?? heuristicSlug ?? normalizedService.replace(/[^a-z0-9]/g, '');

  // Check AWS inline SVGs
  const inline = AWS_INLINE_SVG[slug];
  if (inline) {
    return 'data:image/svg+xml;base64,' + Buffer.from(inline).toString('base64');
  }

  // Check general inline SVGs
  const generalInline = INLINE_SVG[slug];
  if (generalInline) {
    const colored = generalInline.replace(/currentColor/g, `#${color.replace('#', '')}`);
    return 'data:image/svg+xml;base64,' + Buffer.from(colored).toString('base64');
  }

  // If we found a mapped slug, try CDN
  if (mappedSlug) {
    return `https://cdn.simpleicons.org/${slug}/${color.replace('#', '')}`;
  }

  // No mapping found, return fallback SVG as data URI
  const fallbackSvg = getFallbackSVG(service, color);
  return 'data:image/svg+xml;base64,' + Buffer.from(fallbackSvg).toString('base64');
}

export function getFallbackSVG(label: string, color: string = '#999999'): string {
  const words = label.split(/(?=[A-Z])|[\s_-]/).filter(Boolean);
  let chars = '?';
  if (words.length >= 2) {
    chars = (words[0][0] + words[1][0]).toUpperCase();
  } else if (words.length === 1) {
    chars = words[0].slice(0, 2).toUpperCase();
  }
  const displayColor = color === '#f5f5f5' ? '#64748b' : color;

  return `<svg width="36" height="36" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg">
    <circle cx="18" cy="18" r="16" fill="${displayColor}" opacity="0.15"/>
    <circle cx="18" cy="18" r="16" fill="none" stroke="${displayColor}" stroke-width="1.5" opacity="0.4"/>
    <text x="18" y="23" font-size="14" font-weight="600" text-anchor="middle" fill="${displayColor}" font-family="system-ui, -apple-system, sans-serif">
      ${chars}
    </text>
  </svg>`;
}

function shouldUseLightText(hexColor: string): boolean {
  const hex = hexColor.replace('#', '');
  const r = parseInt(hex.substr(0, 2), 16);
  const g = parseInt(hex.substr(2, 2), 16);
  const b = parseInt(hex.substr(4, 2), 16);
  const luminance = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
  return luminance < 0.5;
}

export function hasServiceMapping(service: string): boolean {
  return Boolean(serviceToSlugMap[service.toLowerCase().trim()]);
}
