import { build, context } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

export async function buildViewer(watch = false) {
  const options = { entryPoints: ['src/viewer/session-entry.ts'], bundle: true,
    format: 'iife', globalName: 'DiagramifySession', platform: 'browser', target: 'es2020',
    minify: true, write: false, legalComments: 'none', plugins: [{ name: 'write-viewer', setup(builder) {
      builder.onEnd(async result => {
        if (result.errors.length) return;
        const output = '// Generated by scripts/build-viewer.mjs.\nexport const sessionScript = ' + JSON.stringify(result.outputFiles[0].text) + ';\n';
        const path = 'src/viewer/session.generated.ts';
        if (await readFile(path, 'utf8').catch(() => '') !== output) await writeFile(path, output);
      });
    } }] };
  if (!watch) { await build(options); return; }
  const builder = await context(options);
  await builder.rebuild();
  await builder.watch();
  return builder;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await buildViewer();
